// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type OauthLoginReq struct {
	TenantCode string `json:"tenantCode"`
	Username   string `json:"username"`
	Password   string `json:"password"`
}

type OauthRefreshReq struct {
	Token string `json:"token"`
}

type PageReq struct {
	Page int `json:"page,optional"`
	Size int `json:"size,optional"`
}

type PageResp struct {
	List  interface{} `json:"list"`
	Total int64       `json:"total"`
}

type PasswordChangeReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type PasswordResetReq struct {
	UserId      string `json:"userId"`
	NewPassword string `json:"newPassword"`
}
