// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/saas-zero/saas-zero-auth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/oauth/code",
				Handler: OauthCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oauth/login",
				Handler: OauthLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oauth/menus",
				Handler: OauthMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oauth/password/change",
				Handler: PasswordChangeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oauth/password/reset",
				Handler: PasswordResetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oauth/permissions",
				Handler: OauthPermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oauth/refresh",
				Handler: OauthRefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oauth/userinfo",
				Handler: OauthUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oauth/verify",
				Handler: OauthVerifyHandler(serverCtx),
			},
		},
	)
}
