// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"auth-service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/auth/code",
				Handler: OauthCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oauth/login",
				Handler: OauthLoginHandler(serverCtx),
			},
		},
	)
}
