// Code scaffolded by goctl. Safe to edit.

package logic

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/saas-zero/saas-zero-auth/api/internal/middleware"
	"github.com/saas-zero/saas-zero-auth/api/internal/svc"
	"github.com/saas-zero/saas-zero-auth/api/internal/types"
	"github.com/saas-zero/saas-zero-basedata/rpc/apps"
	"github.com/saas-zero/saas-zero-common/pkg/bcrypt"
	"github.com/saas-zero/saas-zero-common/pkg/errno"
	"github.com/saas-zero/saas-zero-common/pkg/jwt"
	"github.com/zeromicro/go-zero/core/logx"
	"google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/proto"
)

type OauthLoginLogic struct {
	logx.Logger
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewOauthLoginLogic(ctx context.Context, svcCtx *svc.ServiceContext) *OauthLoginLogic {
	return &OauthLoginLogic{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *OauthLoginLogic) OauthLogin(req *types.OauthLoginReq) (resp *types.BaseResp, err error) {
	// 0. Verify captcha
	if req.CaptchaId != "" {
		key := fmt.Sprintf("captcha:%s", req.CaptchaId)
		stored, err := l.svcCtx.Redis.Get(key)
		if err != nil || stored == "" {
			return &types.BaseResp{Code: errno.InvalidParam.Code, Msg: "验证码错误或已过期"}, nil
		}
		l.svcCtx.Redis.Del(key)
		if stored != req.CaptchaVal {
			return &types.BaseResp{Code: errno.InvalidParam.Code, Msg: "验证码错误"}, nil
		}
	}

	authCtx := metadata.NewOutgoingContext(l.ctx, metadata.Pairs(
		"x-user-id", "0",
		"x-user-name", "",
		"x-tenant-id", "0",
	))

	// 1. Look up tenant by code
	tenantResp, err := l.svcCtx.SysTenants.GetTenantByCode(authCtx, &apps.TenantReq{
		Code: proto.String(req.TenantCode),
	})
	if err != nil {
		return &types.BaseResp{Code: errno.TenantNotFound.Code, Msg: errno.TenantNotFound.Msg}, nil
	}
	tenantId := tenantResp.GetData().GetId()
	tenantIdStr := strconv.FormatInt(tenantId, 10)

	// 2. Look up user by tenant + username
	authCtx = metadata.NewOutgoingContext(l.ctx, metadata.Pairs(
		"x-user-id", "0",
		"x-user-name", "",
		"x-tenant-id", tenantIdStr,
	))
	userResp, err := l.svcCtx.SysUsers.GetUserByUsername(authCtx, &apps.UserReq{
		Username: proto.String(req.Username),
	})
	if err != nil {
		return &types.BaseResp{Code: errno.UserNotFound.Code, Msg: errno.UserNotFound.Msg}, nil
	}
	user := userResp.GetData()
	if user == nil {
		return &types.BaseResp{Code: errno.UserNotFound.Code, Msg: errno.UserNotFound.Msg}, nil
	}

	clientIP := middleware.GetClientIP(l.ctx)

	// 2.5 Lockout pre-check: reject if the account is currently locked.
	if user.GetLockoutUntil() > time.Now().UnixMilli() {
		return &types.BaseResp{Code: errno.AccountLocked.Code, Msg: errno.AccountLocked.Msg}, nil
	}

	// 3. Verify password
	if !bcrypt.Verify(req.Password, user.GetPassword()) {
		// Record failure: increments error count, may lock the account, writes login log.
		l.recordLogin(authCtx, user.GetId(), user.GetUsername(), clientIP, tenantId, false, errno.WrongPassword.Msg)
		return &types.BaseResp{Code: errno.WrongPassword.Code, Msg: errno.WrongPassword.Msg}, nil
	}

	// Record success: resets error count, updates last-login info, writes login log.
	l.recordLogin(authCtx, user.GetId(), user.GetUsername(), clientIP, tenantId, true, "登录成功")

	// 4. Fetch role codes for JWT claims so that subsequent API requests
	// can be authorized by CasbinAuth middleware without additional gRPC calls.
	// RoleCodes are embedded in the JWT and extracted by JwtAuth middleware.
	roleCodesResp, err := l.svcCtx.SysUsers.GetUserRoleCodes(authCtx, &apps.IdReq{Id: user.GetId()})
	roleCodes := []string{}
	if err == nil && roleCodesResp != nil {
		roleCodes = roleCodesResp.GetCodes()
	}

	// 5. Generate JWT (JTI auto-generated by jwt.Sign)
	tvKey := fmt.Sprintf("token_version:%d", user.GetId())
	tv, err := l.svcCtx.Redis.Incr(tvKey)
	if err != nil {
		return nil, err
	}
	l.svcCtx.Redis.Expire(tvKey, int(l.svcCtx.Config.JwtExpire)*2)
	claims := &jwt.Claims{
		UserId:       user.GetId(),
		TenantId:     tenantId,
		UserName:     user.GetUsername(),
		RoleCodes:    roleCodes,
		TokenVersion: tv,
	}
	token, err := jwt.Sign(l.svcCtx.Config.JwtSecret, claims, time.Duration(l.svcCtx.Config.JwtExpire)*time.Second)
	if err != nil {
		return nil, err
	}

	// 5. Store token in Redis
	tokenKey := fmt.Sprintf("token:%s", claims.ID)
	if err := l.svcCtx.Redis.Setex(tokenKey, token, int(l.svcCtx.Config.JwtExpire)); err != nil {
		return nil, err
	}

	return &types.BaseResp{
		Code: errno.Success.Code,
		Msg:  "登录成功",
		Data: map[string]interface{}{
			"token":      token,
			"userId":     user.GetIdStr(),
			"username":   user.GetUsername(),
			"nickname":   user.GetNickname(),
			"tenantId":   tenantIdStr,
			"tenantCode": req.TenantCode,
		},
	}, nil
}

// recordLogin 调用 basedata RPC 记录一次登录结果（锁定计数 + 登录审计日志）。
// 失败不阻断登录主流程，仅记录日志。
func (l *OauthLoginLogic) recordLogin(ctx context.Context, userId int64, username, ip string, tenantId int64, success bool, message string) {
	_, err := l.svcCtx.SysUsers.RecordLoginResult(ctx, &apps.LoginRecordReq{
		UserId:   proto.Int64(userId),
		Username: proto.String(username),
		Ip:       proto.String(ip),
		Success:  proto.Bool(success),
		Message:  proto.String(message),
		TenantId: proto.Int64(tenantId),
	})
	if err != nil {
		logx.WithContext(l.ctx).Errorf("record login result error: %v", err)
	}
}
